# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
# Layout/SpaceInsideArrayLiteralBrackets:
#   Enabled: false

plugins:
  - rubocop-rails

Style/ClassAndModuleChildren:
  Enabled: true
  EnforcedStyle: nested

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: true
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Style/AccessModifierDeclarations:
  EnforcedStyle: group
  AllowModifiersOnAttrs: false

Style/TrivialAccessors:
  Enabled: true
  ExactNameMatch: true
  AllowPredicates: true
  AllowDSLWriters: false
  IgnoreClassMethods: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  ConsistentQuotesInMultiline: true

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Enabled: true
  Max: 25
  Exclude:
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
    - 'db/**/*.rb'
    - 'config/routes.rb'
    - 'config/environments/**/*.rb'
    - 'spec/**/*.rb'

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Lint/MissingSuper:
  Enabled: true
  Exclude:
    - 'app/services/**/*'

Rails/I18nLocaleTexts:
  Enabled: false

Layout/ClassStructure:
  Enabled: true
  Categories:
    module_inclusion:
      - include
      - extend
      - prepend
    constants:
      - const
    public_attribute_macros:
      - attr_reader
      - attr_writer
      - attr_accessor
    association:
      - belongs_to
      - has_many
      - has_one
      - has_and_belongs_to_many
    macros:
      - validates
      - validate
      - scope
      - before_validation
      - before_save
      - before_create
      - before_destroy
      - after_validation
      - after_save
      - after_create
      - after_destroy
      - around_save
      - around_create
    public_class_methods:
      - 'def self.'
    initializer:
      - initialize
    public_methods:
      - def
  ExpectedOrder:
    - module_inclusion
    - constants
    - public_attribute_macros
    - association
    - macros
    - public_class_methods
    - initializer
    - public_methods
